import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.concurrent.ExecutionException;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUSER = new javax.swing.JTextField();
        pwdPASS = new javax.swing.JPasswordField();
        bLOGIN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bRESET = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toast = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1.setText("USER NAME :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 100, 86, 17);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel2.setText("PASSWORD :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(149, 170, 100, 17);

        txtUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUSERActionPerformed(evt);
            }
        });
        txtUSER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUSERKeyPressed(evt);
            }
        });
        jPanel1.add(txtUSER);
        txtUSER.setBounds(310, 90, 140, 30);

        pwdPASS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdPASSKeyPressed(evt);
            }
        });
        jPanel1.add(pwdPASS);
        pwdPASS.setBounds(310, 160, 140, 30);

        bLOGIN.setText("LOGIN");
        bLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLOGINActionPerformed(evt);
            }
        });
        bLOGIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bLOGINKeyPressed(evt);
            }
        });
        jPanel1.add(bLOGIN);
        bLOGIN.setBounds(400, 240, 80, 23);

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel3.setText("LOGIN PAGE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 0, 157, 42);

        bRESET.setText("RESET");
        bRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRESETActionPerformed(evt);
            }
        });
        jPanel1.add(bRESET);
        bRESET.setBounds(290, 240, 70, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 40, 240, 236);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 0, 260, 360);

        toast.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jPanel1.add(toast);
        toast.setBounds(70, 300, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLOGINActionPerformed
       // System.out.print(txtUSER.getText()); //printing user name
        String un=txtUSER.getText();
        String pwd=pwdPASS.getText();
        
       /* try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/customer?","root","");
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("select* from cust");
        while(rs.next())
            System.out.println(rs.getInt("cust_id"));
            con.close();    
        }
        catch(Exception e)
        {
         System.out.print (e);
        }*/
        if(un.equals("anandhu")&&pwd.equals("anandhu"))
        {
            //System.out.print("success");
            new Welcome().setVisible(true);
            this.dispose();
        }
        else
        {
        toast.setText("Oops Try Again *_*");
        }
        
    }//GEN-LAST:event_bLOGINActionPerformed

    private void txtUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUSERActionPerformed
       
    }//GEN-LAST:event_txtUSERActionPerformed

    private void bRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRESETActionPerformed
        txtUSER.setText(null);
        pwdPASS.setText(null);
    }//GEN-LAST:event_bRESETActionPerformed

    private void txtUSERKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUSERKeyPressed
        // TODO add your handling code here:
        int a=evt.getKeyCode();
        if (a==10)pwdPASS.requestFocus();
    }//GEN-LAST:event_txtUSERKeyPressed

    private void bLOGINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bLOGINKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLOGINKeyPressed

    private void pwdPASSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPASSKeyPressed
        // TODO add your handling code here:
        int a=evt.getKeyCode();
        if (a==10)bLOGIN.requestFocus();
    }//GEN-LAST:event_pwdPASSKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLOGIN;
    private javax.swing.JButton bRESET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwdPASS;
    private javax.swing.JLabel toast;
    private javax.swing.JTextField txtUSER;
    // End of variables declaration//GEN-END:variables
}
